[build]
  publish = "build"
  command = "npm run build:safe"
  base = "."
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional --legacy-peer-deps"
  DISABLE_ESLINT_PLUGIN = "true"
  LANG = "en_US.UTF-8"
  LC_ALL = "en_US.UTF-8"

# Branch-specific builds
[context.production]
  command = "npm run build:safe"

[context.deploy-preview]
  command = "npm run build:safe"

[context.branch-deploy]
  command = "npm run build:safe"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true