[build]
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200